#!/usr/bin/env python

import sys


def main():
    """ Pre-commit hook for git.
        Called with no parameters before obtaining the proposed commit log
        message and making a commit. 
    """
    print "[POLICY] No commits should be done on the production server."
    return 1


if __name__ == "__main__":
    sys.exit(main())
