# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20090106014008) do

  create_table "assignments", :force => true do |t|
    t.text    "ExpoCode"
    t.text    "project"
    t.text    "current_status"
    t.text    "cchdo_contact"
    t.text    "data_contact"
    t.text    "action"
    t.text    "parameter"
    t.text    "history"
    t.date    "changed"
    t.text    "notes"
    t.integer "priority"
    t.date    "deadline"
    t.string  "manager"
  end

  create_table "audit_trails", :force => true do |t|
    t.integer "record_id"
    t.string  "record_type"
    t.string  "event"
    t.integer "user_id"
    t.date    "time"
  end

  create_table "codes", :force => true do |t|
    t.integer "Code"
    t.text    "Status"
  end

  create_table "contacts", :force => true do |t|
  end

  create_table "cruises", :force => true do |t|
    t.text "ExpoCode"
    t.text "Line"
    t.text "Country"
    t.text "Chief_Scientist"
    t.date "Begin_Date"
    t.date "EndDate"
    t.text "Ship_Name"
    t.text "Alias"
    t.text "Group"
  end

  create_table "documents", :force => true do |t|
    t.text "Size"
    t.text "FileType"
    t.text "FileName"
    t.text "ExpoCode"
    t.text "Files"
    t.date "LastModified"
    t.text "Modified"
  end

  create_table "events", :force => true do |t|
    t.text "ExpoCode"
    t.text "First_Name"
    t.text "LastName"
    t.text "Data_Type"
    t.date "Date_Entered"
    t.text "Summary"
    t.text "Note"
  end

  create_table "map_images", :force => true do |t|
    t.string   "expocode",                                            :null => false
    t.string   "line",                     :default => "Cruise"
    t.string   "west",                     :default => "179W"
    t.string   "east",                     :default => "179E"
    t.string   "south",                    :default => "80S"
    t.string   "north",                    :default => "80N"
    t.string   "label_mod",                :default => "12"
    t.string   "font_type",                :default => "1"
    t.string   "font_size",                :default => "8"
    t.string   "angle",                    :default => "25.0"
    t.string   "justify",                  :default => "LT"
    t.string   "label_color",              :default => "BLACK"
    t.string   "x_shift",                  :default => "0.1i"
    t.string   "y_shift",                  :default => "0.1i"
    t.string   "lon_annot",                :default => "20"
    t.string   "lat_annot",                :default => "10"
    t.string   "annot_font_size",          :default => "12"
    t.string   "header_font",              :default => "1"
    t.string   "header_font_size",         :default => "18"
    t.string   "ocean_color",              :default => "100/180/255"
    t.string   "land_color",               :default => "BLACK"
    t.string   "coastline_color",          :default => "BLACK"
    t.string   "coastline_width",          :default => "0.00i"
    t.string   "map_frame_width",          :default => "6.0i"
    t.string   "station_size_inches",      :default => "0.04i"
    t.string   "station_color",            :default => "255/48/48"
    t.string   "station_outline_color",    :default => "139/0/0"
    t.string   "station_outline_width",    :default => "0.0i"
    t.string   "cruise_line_width_inches", :default => "0.01i"
    t.string   "cruise_line_color",        :default => "BLACK"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "maps", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "parameter_descriptions", :force => true do |t|
    t.string "Parameter"
    t.string "FullName"
    t.string "Description"
    t.string "Units"
    t.string "Range"
    t.string "Alias"
    t.string "Group"
  end

  create_table "parameter_groups", :force => true do |t|
    t.text "group"
    t.text "parameters"
  end

  create_table "parameters", :force => true do |t|
    t.text "ExpoCode"
    t.text "SALNTY"
    t.text "SALNTY_PI"
    t.text "OXYGEN"
    t.text "OXYGEN_PI"
    t.text "SILCAT"
    t.text "SILCAT_PI"
    t.text "NITRAT"
    t.text "NITRAT_PI"
    t.text "NITRIT"
    t.text "NITRIT_PI"
    t.text "PHSPHT"
    t.text "PHSPHT_PI"
    t.text "CFC-11"
    t.text "CFC-11_PI"
    t.text "CFC-12"
    t.text "CFC-12_PI"
    t.text "TRITUM"
    t.text "TRITUM_PI"
    t.text "HELIUM"
    t.text "HELIUM_PI"
    t.text "DELHE3"
    t.text "DELHE3_PI"
    t.text "DELC14"
    t.text "DELC14_PI"
    t.text "DELC13"
    t.text "DELC13_PI"
    t.text "KR-85"
    t.text "KR-85_PI"
    t.text "ARGON"
    t.text "ARGON_PI"
    t.text "AR-39"
    t.text "AR-39_PI"
    t.text "NEON"
    t.text "NEON_PI"
    t.text "RA-228"
    t.text "RA-228_PI"
    t.text "RA-226"
    t.text "RA-226_PI"
    t.text "O18/O16"
    t.text "O18/O16_PI"
    t.text "SR-90"
    t.text "SR-90_PI"
    t.text "CS-137"
    t.text "CS-137_PI"
    t.text "TCARBN"
    t.text "TCARBN_PI"
    t.text "ALKALI"
    t.text "ALKALI_PI"
    t.text "PCO2"
    t.text "PCO2_PI"
    t.text "PH"
    t.text "PH_PI"
    t.text "CFC113"
    t.text "CFC113_PI"
    t.text "CCL4"
    t.text "CCL4_PI"
    t.text "IODATE"
    t.text "IODATE_PI"
    t.text "IODIDE"
    t.text "IODIDE_PI"
    t.text "NH4"
    t.text "NH4_PI"
    t.text "CH4"
    t.text "CH4_PI"
    t.text "DON"
    t.text "DON_PI"
    t.text "N2O"
    t.text "N2O_PI"
    t.text "CHLORA"
    t.text "CHLORA_PI"
    t.text "PPHYTN"
    t.text "PPHYTN_PI"
    t.text "DMS"
    t.text "DMS_PI"
    t.text "BARIUM"
    t.text "BARIUM_PI"
    t.text "POC"
    t.text "POC_PI"
    t.text "PON"
    t.text "PON_PI"
    t.text "BACT"
    t.text "BACT_PI"
    t.text "DOC"
    t.text "DOC_PI"
    t.text "COMON"
    t.text "COMON_PI"
    t.text "C13ERR"
    t.text "C13ERR_PI"
    t.text "C14ERR"
    t.text "C14ERR_PI"
    t.text "BTLNBR"
    t.text "BTLNBR_PI"
    t.text "CASTNO"
    t.text "CASTNO_PI"
    t.text "CTDOXY"
    t.text "CTDOXY_PI"
    t.text "CTDPRS"
    t.text "CTDPRS_PI"
    t.text "CTDRAW"
    t.text "CTDRAW_PI"
    t.text "CTDSAL"
    t.text "CTDSAL_PI"
    t.text "CTDTMP"
    t.text "CTDTMP_PI"
    t.text "FLUOR"
    t.text "FLUOR_PI"
    t.text "NO2+NO3"
    t.text "NO2+NO3_PI"
    t.text "PCO2TMP"
    t.text "PCO2TMP_PI"
    t.text "PHTEMP"
    t.text "PHTEMP_PI"
    t.text "REVPRS"
    t.text "REVPRS_PI"
    t.text "REVTMP"
    t.text "REVTMP_PI"
    t.text "SAMPNO"
    t.text "SAMPNO_PI"
    t.text "STNNBR"
    t.text "STNNBR_PI"
    t.text "TDN"
    t.text "TDN_PI"
    t.text "THETA"
    t.text "THETA_PI"
    t.text "XMISS"
    t.text "XMISS_PI"
    t.text "AOU"
    t.text "AOU_PI"
    t.text "ARAB"
    t.text "ARAB_PI"
    t.text "AZOTE"
    t.text "AZOTE_PI"
    t.text "BRDU"
    t.text "BRDU_PI"
    t.text "CALCIUM"
    t.text "CALCIUM_PI"
    t.text "CU"
    t.text "CU_PI"
    t.text "DCNS"
    t.text "DCNS_PI"
    t.text "DELHE4"
    t.text "DELHE4_PI"
    t.text "DELHER"
    t.text "DELHER_PI"
    t.text "DIC"
    t.text "DIC_PI"
    t.text "FUC"
    t.text "FUC_PI"
    t.text "GAL"
    t.text "GAL_PI"
    t.text "GLU"
    t.text "GLU_PI"
    t.text "HELIER"
    t.text "HELIER_PI"
    t.text "IOD-129"
    t.text "IOD-129_PI"
    t.text "MAN"
    t.text "MAN_PI"
    t.text "MCHFRM"
    t.text "MCHFRM_PI"
    t.text "NEONER"
    t.text "NEONER_PI"
    t.text "NI"
    t.text "NI_PI"
    t.text "NO2"
    t.text "NO2_PI"
    t.text "PEUK"
    t.text "PEUK_PI"
    t.text "PRO"
    t.text "PRO_PI"
    t.text "RHAM"
    t.text "RHAM_PI"
    t.text "SF6"
    t.text "SF6_PI"
    t.text "SYN"
    t.text "SYN_PI"
    t.text "TOC"
    t.text "TOC_PI"
    t.text "TRITER"
    t.text "TRITER_PI"
    t.text "CF12ER"
    t.text "CF12ER_PI"
    t.text "PHPUNC"
    t.text "PHPUNC_PI"
    t.text "SILUNC"
    t.text "SILUNC_PI"
    t.text "NRAUNC"
    t.text "NRAUNC_PI"
    t.text "NRIUNC"
    t.text "NRIUNC_PI"
  end

  create_table "priorities", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "sea_hunts", :force => true do |t|
    t.string  "cruise_name"
    t.string  "dates"
    t.string  "location"
    t.string  "status"
    t.string  "contact-1"
    t.string  "email"
    t.string  "phone"
    t.string  "institution"
    t.string  "institution-2"
    t.string  "notes"
    t.string  "country",                                :default => ""
    t.integer "display_status",                         :default => 2,            :null => false
    t.string  "duration",                               :default => ""
    t.string  "frequency",                              :default => ""
    t.string  "ship",                                   :default => ""
    t.string  "url",                                    :default => ""
    t.date    "real_date",                              :default => '1001-01-01', :null => false
    t.binary  "cruise_track_thumb", :limit => 16777215,                           :null => false
    t.string  "basin",                                  :default => ""
  end

  create_table "seahunts", :force => true do |t|
  end

  create_table "sessions", :force => true do |t|
    t.string   "session_id"
    t.text     "data"
    t.datetime "updated_at"
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "stations", :force => true do |t|
    t.string "ExpoCode"
    t.string "FileName"
    t.string "Basin"
    t.text   "Track"
    t.text   "lat"
    t.text   "long"
    t.text   "stnnum"
    t.text   "event_code"
    t.text   "cor_depth"
    t.text   "max_press"
  end

  create_table "submissions", :force => true do |t|
    t.text    "name"
    t.text    "institute"
    t.text    "Country"
    t.text    "email"
    t.text    "public"
    t.text    "ExpoCode"
    t.text    "Ship_Name"
    t.text    "Line"
    t.date    "cruise_date"
    t.text    "action"
    t.text    "notes"
    t.text    "file"
    t.boolean "assigned"
    t.boolean "assimilated"
  end

  create_table "tracks", :force => true do |t|
    t.string "ExpoCode"
    t.string "FileName"
    t.string "Basin"
    t.text   "Track"
  end

  create_table "users", :force => true do |t|
    t.string "username"
    t.string "password_salt"
    t.string "password_hash"
  end

end
